# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder File.join("..", "public", ""), "/var/www/html"
  #web app port
  config.vm.network :forwarded_port, host: 8080, guest: 80

  config.vm.provider "virtualbox" do |v|
      v.memory = 1548
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
  SHELL

end
